server {
    listen 80;
    server_name localhost;
    root /var/www/html; # พาธเริ่มต้นใน Container [11]
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # ส่งไฟล์ .php ไปให้ backend-php (PHP-FPM) ประมวลผล [1, 12]
    location ~ \.php$ {
        fastcgi_pass backend-php:9000; # ชี้ไปที่ชื่อ Service ของ PHP [1]
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
